### ISSUE TITLE
Taxonomy of communication devices : where ?

### ISSUE THREAD

**Issue by GenEars** [thesmartenergy/seas#39]
Dear SEAS team,
There's a comment in *CommunicationOntology-1.0.ttl* (see [here](https://github.com/thesmartenergy/seas/blob/ae36f017cd343f1d675b65f72a585bfa82edfe56/src/main/ontop/1.0/CommunicationOntology-1.0.ttl#L81)) saying that there is some available "*taxonomy of communication devices*".
I was not capable to find it in the https://github.com/thesmartenergy/seas ... where is it available ? is it using SKOS ?

Best regards,
LTa

**Comment by maximelefrancois86** [comment]
The taxonomy consists of the hierarchy of sub-classes of `seas:CommunicationDevice`:

![image](https://user-images.githubusercontent.com/11416248/145812638-8ecbc404-9900-4948-ba4e-5afc4c759560.png)

**Comment by GenEars** [comment]
Hi @maximelefrancois86 
Thanks for the answer.
What about devices that are both "wire" and "wireless" (e.g. multi-purpose routers)?
=> Should we make instances at the "CommunicationDevice" level ?
=> Would you agree extending this taxonomy with SKOS concepts ?

**Comment by maximelefrancois86** [comment]
An individual can belong to two classes.  The device would have two distinct communication points (call them interfaces, or ports, if you wish)

Yes you may extend this taxonomy with SKOS concepts. Please try to remain in the OWL2 DL profile though. This is a design choice for the SEAS ontology

**Comment by GenEars** [comment]
Thanks. That's clear and sound.
